server:
    port: 8083

spring:
    application:
      name: Profile-Service  
        
eureka:
   client:
     serviceUrl:
       defaultZone: http://localhost:8081/eureka/
     instance:
      leaseRenewalIntervalInSeconds: 5
      lease-expiration-duration-in-seconds: 5