server:
  port: 9999


zuul:
  ignored-services: '*'
  routes:
    Content-Service:
      path: /games/**
      stripPrefix: false
    Profile-Service:
      path: /users/**
      stripPrefix: false
    Client-Side Load-Balancer:
      path: /invoke/**
      stripPrefix: false
      
eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8081/eureka/

management:
  security:
    enabled: false
