server:
  port: 9999


zuul:
#  ignored-services: '*'
  routes:
    Profile-Service:
      path: /games/**
      stripPrefix: false
    Content-Service:
      path: /games/**
      stripPrefix: false
      
eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8081/eureka/

management:
  security:
    enabled: false
