server:
     port: 8082

spring:
    application:
      name: MFU_Games-service
        
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8081/eureka/
    healthcheck:
      enabled: true
    instance:
      leaseRenewalIntervalInSeconds: 5
      lease-expiration-duration-in-seconds: 5
      